name: openmmtools
channels:
    - conda-forge
    - omnia
dependencies:
    - python
    - setuptools
    - openmm >=7.3
    - cython
    - numpy
    - scipy
    - six
    - parmed
    - mdtraj
    - numpydoc
    - netcdf4 >=1.4.2 # after bugfix: "always return masked array by default, even if there are no masked values"
    - libnetcdf >=4.6.2 # workaround for libssl issues
    - sphinxcontrib-bibtex
    - mpiplus
    - pymbar
    - pyyaml
